In [2]:
data = pd.read_csv("C:\\Users\\maeve\\Downloads\\Social_Media_Advertising.csv.zip")

In [3]:
data.head()

,Campaign_ID,Target_Audience,Campaign_Goal,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Company
0,529013,Men 35-44,Product Launch,15 Days,Instagram,0.15,$500.00,5.790000,Las Vegas,Spanish,500,3000,7,Health,2022-02-25,Aura Align
1,275352,Women 45-60,Market Expansion,15 Days,Facebook,0.01,$500.00,7.210000,Los Angeles,French,500,3000,5,Home,2022-05-12,Hearth Harmony
2,692322,Men 45-60,Product Launch,15 Days,Instagram,0.08,$500.00,0.430000,Austin,Spanish,500,3000,9,Technology,2022-06-19,Cyber Circuit
3,675757,Men 25-34,Increase Sales,15 Days,Pinterest,0.03,$500.00,0.909824,Miami,Spanish,293,1937,1,Health,2022-09-08,Well Wish
4,535900,Men 45-60,Market Expansion,15 Days,Pinterest,0.13,$500.00,1.422828,Austin,French,293,1937,1,Home,2022-08-24,Hearth Harmony

In [4]:
data.columns

Index(['Campaign_ID', 'Target_Audience', 'Campaign_Goal', 'Duration',
       'Channel_Used', 'Conversion_Rate', 'Acquisition_Cost', 'ROI',
       'Location', 'Language', 'Clicks', 'Impressions', 'Engagement_Score',
       'Customer_Segment', 'Date', 'Company'],
      dtype='object')

In [5]:
data.describe()

,Campaign_ID,Conversion_Rate,ROI,Clicks,Impressions,Engagement_Score
count,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000
mean,550444.804487,0.080009,3.177691,18153.670370,56034.236387,4.369217
std,260252.586037,0.040563,2.461200,11027.023294,32583.136334,3.156492
min,100001.000000,0.010000,0.000000,293.000000,1937.000000,1.000000
25%,325003.500000,0.050000,0.930000,8821.000000,28362.000000,1.000000
50%,551164.500000,0.080000,2.670000,17230.000000,54098.000000,4.000000
75%,776284.500000,0.110000,5.330000,26808.000000,80925.250000,7.000000
max,999998.000000,0.150000,8.000000,40000.000000,120000.000000,10.000000

In [6]:

# Grouping by 'Campaign_Goal' and 'Channel_Used' and calculating the mean ROI
channel_goal_data = data.groupby(['Campaign_Goal', 'Channel_Used'])[['ROI']].mean()

In [39]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Group by 'Campaign_Goal' and 'Channel_Used' and calculate the mean ROI
channel_goal_data = data.groupby(['Campaign_Goal', 'Channel_Used'])[['ROI']].mean()

# Pivot the table so that 'Campaign_Goal' is on the rows, 'Channel_Used' on the columns, and 'ROI' as the value
heatmap_data = channel_goal_data.pivot(index='Campaign_Goal', columns='Channel_Used', values='ROI')

# Set the width and height of the figure
plt.figure(figsize=(14,7))

# Add title
plt.title("ROI by Campaign Goal and Channel Used")

# Create the heatmap
sns.heatmap(heatmap_data, annot=True, cmap="YlGnBu")

# Add labels for the axes
plt.xlabel("Channel Used")
plt.ylabel("Campaign Goal")

# Display the plot
plt.show()

KeyError: 'Campaign_Goal'

In [37]:
print(data.columns)

Index(['Campaign_ID', 'Target_Audience', 'Campaign_Goal', 'Duration',
       'Channel_Used', 'Conversion_Rate', 'Acquisition_Cost', 'ROI',
       'Location', 'Language', 'Clicks', 'Impressions', 'Engagement_Score',
       'Customer_Segment', 'Date', 'Company'],
      dtype='object')